define(['backbone', 'utils/validation_rules', 'backbone-validation'], function(Backbone, ValidationRules) {

    _.extend(Backbone.Validation.patterns, {
        wwsdash: ValidationRules.wwsdash.regex,
        wwsldash: ValidationRules.wwsldash.regex,
        wwsbdash: ValidationRules.wwsbdash.regex,
        wwdash: ValidationRules.wwdash.regex,
        datetime: ValidationRules.datetime.regex,
        edate: ValidationRules.edate.regex,
        word: ValidationRules.word.regex,
        fcode: ValidationRules.fcode.regex,
        time: ValidationRules.time.regex,
        sequence: ValidationRules.sequence.regex,
        address: ValidationRules.address.regex,
        array: ValidationRules.array.regex,
        country: ValidationRules.country.regex,
        visit: ValidationRules.visit.regex,
        twopath: ValidationRules.twopath.regex,
        // wwsdash: /^(\w|\s|\-)+$/,
        // wwsldash: /^(\w|\s|\-|\/)+$/,
        // wwsbdash: /^(\w|\s|\-|\(|\))+$/,
        // wwdash: /^(\w|\-)+$/,
        // datetime: /^\d\d-\d\d-\d\d\d\d \d\d:\d\d$/,
        // edate: /^\d\d-\d\d-\d\d\d\d$/,
        // word: /^\w+$/,
        // fcode: /^DLS\-(MX|IN|CY|BI)\-\d\d\d\d$/i,
        // time: /^\d\d:\d\d$/,
        // sequence: /^[>;\s\w+\n\(\)\.\|]+$/,
        // address: /^(\w|\s|\-|\n|,)+$/,
        // array: /^[\d+(.\d+)?),]+$/,
        // country: /^(\w|\s|\-|,|\(|\)|')+$/,
        // visit: /^\w+\d+-\d+$/,
        // twopath: /^(\w|-)+\/?(\w|-)+$/,
    })

    _.extend(Backbone.Validation.messages, {
        required: 'This field is required',
        wwsdash: ValidationRules.wwsdash.message,
        wwsldash: ValidationRules.wwsldash.message,
        wwsbdash: ValidationRules.wwsbdash.message,
        wwdash: ValidationRules.wwdash.message,
        datetime: ValidationRules.datetime.message,
        edate: ValidationRules.edate.message,
        word: ValidationRules.word.message,
        fcode: ValidationRules.fcode.message,
        time: ValidationRules.time.message,
        sequence: ValidationRules.sequence.message,
        address: ValidationRules.address.message,
        array: ValidationRules.array.message,
        country: ValidationRules.country.message,
        visit: ValidationRules.visit.message,
        twopath: ValidationRules.twopath.message,
        // wwsdash: 'This field must contain only letters, numbers, spaces, underscores, and dashes',
        // wwdash: 'This field must contain only letters, numbers, underscores, and dashes',
        // edate: 'Please specify a valid date (european style)',
        // word: 'This field must contain only letters and numbers',
        // fcode: 'This field must be of the format DLS-XX-XXXX',
        // datetime: 'This field must be of the format DD-MM-YYYY HH:MM',
        // time: 'This field must be of the format HH:MM',
        // sequence: 'This field may only contain word characters and line returns',
        // address: 'This field may only contain word character, spaces, and line returns',
        // array: 'This field may only contain numbers and commas',
        // country: 'This field must contain only letters, numbers, spaces, underscores, dashes, and commas',
        // visit: 'This field must be of the format xxx123-123',
        // twopath: 'This field can hold a path with two folders',
    })

})
