name: Build and Test SynchWeb

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash
    working-directory: ./api
    
jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  phpbuild:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP 7.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  phplint:
    needs: phpbuild
    runs-on: ubuntu-latest
    steps:
      - name: Psalm Linting
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true

  phptest:
    needs: phpbuild
    runs-on: ubuntu-latest
    steps:
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text

  js_build_lint_and_test:
    name: JavaScript build, lint and test
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: JavaScript build, lint and test
        working-directory: ./client
        run: |
              npm ci
              npm run build
              npm run test
              npm run lint
              npm run lint-vue
