name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Psalm Linting
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true

  phptest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          dir: api
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
